; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; =========================================================================
; 기본 플랫폼(espressif32)에는 I2S0, I2S1채널 동기화를 위한 최신 표준 드라이버(driver/i2s_std.h)가 
; 포함되지 않아 컴파일 에러 발생. 최신 아두이노 코어를 지원하는 pioarduino 커뮤니티 빌드 강제 적용. 
; =========================================================================

[platformio]
default_envs = esp32dev

; 집 테스트 환경(일반 ESP32)
[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = gilmaimon/ArduinoWebsockets @ ^0.5.3
build_flags = -D BOARD_ESP32_STD

; 브레드보드 테스트 환경(ESP32-S3)
[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = gilmaimon/ArduinoWebsockets @ ^0.5.3
build_flags = -D BOARD_ESP32_S3

; 데모 제작용 환경(FeatherS3)